- name: Clear files on cluster hosts
  hosts: client_machine
  become: yes  # Only if you need elevated privileges
  tasks:
    - name: Find all files in ~/coursework directory
      find:
        paths: "/home/ec2-user/coursework"
        file_type: any
      register: files_to_delete
