
- name: distribute part experiment_ids file to client
  hosts: host_machine
  become: yes
  tasks:
    - name: Install yum packages
      ansible.builtin.yum:
        name: 
        - wget
        - git

    - name: delete project file 
      file:
        path: /home/ec2-user/coursework
        state: absent

    - name: Clone project repository
      git:
        repo: 'https://github.com/niehao610/coursework.git'
        dest: '/home/ec2-user/coursework'
        clone: yes
        update: yes 

    - name: delete  file 
      file:
        path: /data/coursework/data
        state: absent

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "/data/coursework/data"
        state: directory
        mode: '0755'
        
    - name: Extract file
      ansible.builtin.unarchive:
        src: "/home/ec2-user/coursework/uniprotkb_proteome_UP000005640_2023_10_05.zip"
        dest: "/data/coursework/data/"

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "/data/coursework/data/split_ids/"
        state: directory
        mode: '0755'

    - name: enter destination directory exists
      ansible.builtin.file:
        path: "/home/ec2-user/coursework"
        state: directory

    - name: spilt experiment data, discript to client
      script: /home/ec2-user/coursework/prepare_experiment.sh
    
    - name: "Copy part file to client2"
      command: scp  /data/coursework/data/split_ids/datafile_part_ab   ec2-user@ec2-3-11-209-4.eu-west-2.compute.amazonaws.com:/tmp/rawdata.fasta
            
#    - name: Copy split file to client
#      ansible.builtin.copy:
#         src: "/data/coursework/data/split_ids/{{ item.src }}"
#         dest: "/home/ec2-user/coursework/data/rawdata.fasta"
#         remote_src: no
#         become: yes
#         loop:
#         - { src: 'datafile_part_ab', host: 'cluster_0' }
#         - { src: 'datafile_part_ac', host: 'cluster_1' }
#         - { src: 'datafile_part_ad', host: 'cluster_2' }
#         - { src: 'datafile_part_ae', host: 'cluster_3' }
#         - { src: 'datafile_part_af', host: 'cluster_4' }
#         when: inventory_hostname == hostvars[item.host].ansible_host