
- name: distribute part experiment_ids file to client
  hosts: host_machine
  become: yes
  tasks:
    - name: Install yum packages
      ansible.builtin.yum:
        name: 
        - wget
        - git

    - name: delete project file 
      file:
        path: /home/ec2-user/coursework
        state: absent

    - name: Clone project repository
      git:
        repo: 'https://github.com/niehao610/coursework.git'
        dest: '/home/ec2-user/coursework'
        clone: yes
        update: yes 

    - name: delete  file 
      file:
        path: /data/coursework/data
        state: absent

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "/data/coursework/data"
        state: directory
        mode: '0755'
        
    - name: Extract file
      ansible.builtin.unarchive:
        src: "/home/ec2-user/coursework/uniprotkb_proteome_UP000005640_2023_10_05.zip"
        dest: "/data/coursework/data/"

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "/data/coursework/data/split_ids/"
        state: directory
        mode: '0755'

    - name: enter destination directory exists
      ansible.builtin.file:
        path: "/home/ec2-user/coursework"
        state: directory

    - name: spilt experiment data, discript to client
      script: /home/ec2-user/coursework/prepare_experiment.sh
    
    - name: pull part file to local
      fetch: 
        src: /data/coursework/data/split_ids/datafile_part_*
        dest: /home/ec2-user/coursework/data/
        