
- name: distribute part experiment_ids file to client
  hosts: host_machine
  become: yes
  tasks:
    - name: Install yum packages
      ansible.builtin.yum:
        name: 
        - wget
        - unzip
 
    - name: Create work dir if it does not exist
      ansible.builtin.file:
        path: "/data/coursework"
        state: directory
        mode: '0755'

    - name: Create  directory split_ids if it does not exist
      ansible.builtin.file:
        path: "/data/coursework/data/split_ids/"
        state: directory
        mode: '0755'
    
    - name: delete zip file 
      file:
        path: /data/coursework/data/uniprotkb_proteome_UP000005640_2023_10_05.zip
        state: absent

    - name: delete extract file 
      file:
        path: /data/coursework/data/uniprotkb_proteome_UP000005640_2023_10_05.fasta
        state: absent

    - name: download raw experiment data file from host
      get_url:
        url: "https://github.com/niehao610/coursework/blob/main/uniprotkb_proteome_UP000005640_2023_10_05.zip"
        dest: "/data/coursework/data/"
    
    - name: Extract file
      ansible.builtin.unarchive:
        src: "/data/coursework/data/uniprotkb_proteome_UP000005640_2023_10_05.zip"
        dest: "/data/coursework/data/"

    - name: download bash script
      get_url:
        url: "https://github.com/niehao610/coursework/blob/main/prepare_experiment.sh"
        dest: "/home/ec2-user/coursework/"

    - name: spilt experiment data, discript to client
      script: /home/ec2_user/coursework/prepare_experiment.sh  

    - name: Copy split file to client
      ansible.builtin.copy:
         src: "/home/ec2-user/coursework/data/split_ids/{{ item.src }}"
         dest: "/home/ec2-user/coursework/data/rawdata.fasta"
         remote_src: no
         become: yes
         loop:
         - { src: 'datafile_part_ab', host: 'client' }
         - { src: 'datafile_part_ac', host: 'cluster_1' }
         - { src: 'datafile_part_ad', host: 'cluster_2' }
         - { src: 'datafile_part_ae', host: 'cluster_3' }
         - { src: 'datafile_part_af', host: 'cluster_4' }
         when: inventory_hostname == hostvars[item.host].ansible_host