- name: exec script
  hosts: host
  tasks:
    - name: enter destination directory exists
      ansible.builtin.file:
        path: "/data/coursework"
        state: directory

    - name: Run the Python file
      ansible.builtin.command:
        cmd: "python  ./pipeline_script.py  ./data/experiment_ids.txt {{ rank }}"
      args:
        chdir: "/data/coursework"
  