- name: exec script
  hosts: host
  tasks:
    - name: enter destination directory exists
      ansible.builtin.file:
        path: "/home/ec2-user/coursework/coursework"
        state: directory

    - name: Run the Python file
      ansible.builtin.command:
        cmd: "python  ./pipeline_script.py  ./home/ec2-user/coursework/data/rawdata.fasta {{ rank }}"
      args:
        chdir: "/home/ec2-user/coursework/coursework"
  