- name: Setup SSH Keys on client and host machines
  hosts: host
  tasks:
    - name: Create keys
      openssh_keypair:
        path: /home/ec2-user/.ssh/ansible_key
        force: no  
      register: ssh_key

- name: Send Keys to all client machines
  hosts: client_machine
  tasks:
    - name: Add the public key to remote machine
      authorized_key:
        user: ec2-user
        state: present
        key: "{{ hostvars['ec2-18-170-108-44.eu-west-2.compute.amazonaws.com']['ssh_key']['public_key'] }}"
