- name: setup dependencies
  hosts: client_machine
  become: true
  tasks:

    - name: Install yum packages
      ansible.builtin.yum:
        name: 
        - python3
        - unzip
        - git
        
    - name: Install biopython python package
      ansible.builtin.pip:
        name: biopython
        executable: pip3

    - name: Install numpy python package
      ansible.builtin.pip:
        name: numpy
        executable: pip3

    - name: Install numpy python package
      ansible.builtin.pip:
        name: numpy
        executable: pip3

    - name: Install torch python package
      ansible.builtin.pip:
        name: 
        - torch 
        - torchvision 
        - torchaudio
        executable: pip3
        extra_args: --index-url https://download.pytorch.org/whl/cpu

